// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conveyormessage.proto

package nettytest;

public final class ConvQClientProto {
  private ConvQClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage() {
      initFields();
    }
    private ClientMessage(boolean noInit) {}
    
    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nettytest.ConvQClientProto.internal_static_nettytest_ClientMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nettytest.ConvQClientProto.internal_static_nettytest_ClientMessage_fieldAccessorTable;
    }
    
    public static final class ClientRequest extends
        com.google.protobuf.GeneratedMessage {
      // Use ClientRequest.newBuilder() to construct.
      private ClientRequest() {
        initFields();
      }
      private ClientRequest(boolean noInit) {}
      
      private static final ClientRequest defaultInstance;
      public static ClientRequest getDefaultInstance() {
        return defaultInstance;
      }
      
      public ClientRequest getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nettytest.ConvQClientProto.internal_static_nettytest_ClientMessage_ClientRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nettytest.ConvQClientProto.internal_static_nettytest_ClientMessage_ClientRequest_fieldAccessorTable;
      }
      
      public enum RequestType
          implements com.google.protobuf.ProtocolMessageEnum {
        PUT(0, 0),
        PEEK(1, 1),
        POP(2, 2),
        ;
        
        
        public final int getNumber() { return value; }
        
        public static RequestType valueOf(int value) {
          switch (value) {
            case 0: return PUT;
            case 1: return PEEK;
            case 2: return POP;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
                public RequestType findValueByNumber(int number) {
                  return RequestType.valueOf(number)
        ;        }
              };
        
        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDescriptor().getEnumTypes().get(0);
        }
        
        private static final RequestType[] VALUES = {
          PUT, PEEK, POP, 
        };
        public static RequestType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }
        private final int index;
        private final int value;
        private RequestType(int index, int value) {
          this.index = index;
          this.value = value;
        }
        
        static {
          nettytest.ConvQClientProto.getDescriptor();
        }
        
        // @@protoc_insertion_point(enum_scope:nettytest.ClientMessage.ClientRequest.RequestType)
      }
      
      // required .nettytest.ClientMessage.ClientRequest.RequestType req = 1;
      public static final int REQ_FIELD_NUMBER = 1;
      private boolean hasReq;
      private nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType req_;
      public boolean hasReq() { return hasReq; }
      public nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType getReq() { return req_; }
      
      // optional bytes msg = 2;
      public static final int MSG_FIELD_NUMBER = 2;
      private boolean hasMsg;
      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMsg() { return hasMsg; }
      public com.google.protobuf.ByteString getMsg() { return msg_; }
      
      private void initFields() {
        req_ = nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType.PUT;
      }
      public final boolean isInitialized() {
        if (!hasReq) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasReq()) {
          output.writeEnum(1, getReq().getNumber());
        }
        if (hasMsg()) {
          output.writeBytes(2, getMsg());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasReq()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, getReq().getNumber());
        }
        if (hasMsg()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMsg());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ClientRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(nettytest.ConvQClientProto.ClientMessage.ClientRequest prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private nettytest.ConvQClientProto.ClientMessage.ClientRequest result;
        
        // Construct using nettytest.ConvQClientProto.ClientMessage.ClientRequest.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new nettytest.ConvQClientProto.ClientMessage.ClientRequest();
          return builder;
        }
        
        protected nettytest.ConvQClientProto.ClientMessage.ClientRequest internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new nettytest.ConvQClientProto.ClientMessage.ClientRequest();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDescriptor();
        }
        
        public nettytest.ConvQClientProto.ClientMessage.ClientRequest getDefaultInstanceForType() {
          return nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public nettytest.ConvQClientProto.ClientMessage.ClientRequest build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private nettytest.ConvQClientProto.ClientMessage.ClientRequest buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public nettytest.ConvQClientProto.ClientMessage.ClientRequest buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          nettytest.ConvQClientProto.ClientMessage.ClientRequest returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof nettytest.ConvQClientProto.ClientMessage.ClientRequest) {
            return mergeFrom((nettytest.ConvQClientProto.ClientMessage.ClientRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(nettytest.ConvQClientProto.ClientMessage.ClientRequest other) {
          if (other == nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDefaultInstance()) return this;
          if (other.hasReq()) {
            setReq(other.getReq());
          }
          if (other.hasMsg()) {
            setMsg(other.getMsg());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType value = nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  setReq(value);
                }
                break;
              }
              case 18: {
                setMsg(input.readBytes());
                break;
              }
            }
          }
        }
        
        
        // required .nettytest.ClientMessage.ClientRequest.RequestType req = 1;
        public boolean hasReq() {
          return result.hasReq();
        }
        public nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType getReq() {
          return result.getReq();
        }
        public Builder setReq(nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasReq = true;
          result.req_ = value;
          return this;
        }
        public Builder clearReq() {
          result.hasReq = false;
          result.req_ = nettytest.ConvQClientProto.ClientMessage.ClientRequest.RequestType.PUT;
          return this;
        }
        
        // optional bytes msg = 2;
        public boolean hasMsg() {
          return result.hasMsg();
        }
        public com.google.protobuf.ByteString getMsg() {
          return result.getMsg();
        }
        public Builder setMsg(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasMsg = true;
          result.msg_ = value;
          return this;
        }
        public Builder clearMsg() {
          result.hasMsg = false;
          result.msg_ = getDefaultInstance().getMsg();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:nettytest.ClientMessage.ClientRequest)
      }
      
      static {
        defaultInstance = new ClientRequest(true);
        nettytest.ConvQClientProto.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:nettytest.ClientMessage.ClientRequest)
    }
    
    public static final class ServerResponse extends
        com.google.protobuf.GeneratedMessage {
      // Use ServerResponse.newBuilder() to construct.
      private ServerResponse() {
        initFields();
      }
      private ServerResponse(boolean noInit) {}
      
      private static final ServerResponse defaultInstance;
      public static ServerResponse getDefaultInstance() {
        return defaultInstance;
      }
      
      public ServerResponse getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nettytest.ConvQClientProto.internal_static_nettytest_ClientMessage_ServerResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nettytest.ConvQClientProto.internal_static_nettytest_ClientMessage_ServerResponse_fieldAccessorTable;
      }
      
      public enum ResponseType
          implements com.google.protobuf.ProtocolMessageEnum {
        OK(0, 0),
        ERROR(1, 1),
        ;
        
        
        public final int getNumber() { return value; }
        
        public static ResponseType valueOf(int value) {
          switch (value) {
            case 0: return OK;
            case 1: return ERROR;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
                public ResponseType findValueByNumber(int number) {
                  return ResponseType.valueOf(number)
        ;        }
              };
        
        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDescriptor().getEnumTypes().get(0);
        }
        
        private static final ResponseType[] VALUES = {
          OK, ERROR, 
        };
        public static ResponseType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }
        private final int index;
        private final int value;
        private ResponseType(int index, int value) {
          this.index = index;
          this.value = value;
        }
        
        static {
          nettytest.ConvQClientProto.getDescriptor();
        }
        
        // @@protoc_insertion_point(enum_scope:nettytest.ClientMessage.ServerResponse.ResponseType)
      }
      
      // required .nettytest.ClientMessage.ServerResponse.ResponseType resp = 1;
      public static final int RESP_FIELD_NUMBER = 1;
      private boolean hasResp;
      private nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType resp_;
      public boolean hasResp() { return hasResp; }
      public nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType getResp() { return resp_; }
      
      private void initFields() {
        resp_ = nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType.OK;
      }
      public final boolean isInitialized() {
        if (!hasResp) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasResp()) {
          output.writeEnum(1, getResp().getNumber());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasResp()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, getResp().getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static nettytest.ConvQClientProto.ClientMessage.ServerResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(nettytest.ConvQClientProto.ClientMessage.ServerResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private nettytest.ConvQClientProto.ClientMessage.ServerResponse result;
        
        // Construct using nettytest.ConvQClientProto.ClientMessage.ServerResponse.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new nettytest.ConvQClientProto.ClientMessage.ServerResponse();
          return builder;
        }
        
        protected nettytest.ConvQClientProto.ClientMessage.ServerResponse internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new nettytest.ConvQClientProto.ClientMessage.ServerResponse();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDescriptor();
        }
        
        public nettytest.ConvQClientProto.ClientMessage.ServerResponse getDefaultInstanceForType() {
          return nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public nettytest.ConvQClientProto.ClientMessage.ServerResponse build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private nettytest.ConvQClientProto.ClientMessage.ServerResponse buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public nettytest.ConvQClientProto.ClientMessage.ServerResponse buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          nettytest.ConvQClientProto.ClientMessage.ServerResponse returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof nettytest.ConvQClientProto.ClientMessage.ServerResponse) {
            return mergeFrom((nettytest.ConvQClientProto.ClientMessage.ServerResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(nettytest.ConvQClientProto.ClientMessage.ServerResponse other) {
          if (other == nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDefaultInstance()) return this;
          if (other.hasResp()) {
            setResp(other.getResp());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType value = nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  setResp(value);
                }
                break;
              }
            }
          }
        }
        
        
        // required .nettytest.ClientMessage.ServerResponse.ResponseType resp = 1;
        public boolean hasResp() {
          return result.hasResp();
        }
        public nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType getResp() {
          return result.getResp();
        }
        public Builder setResp(nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasResp = true;
          result.resp_ = value;
          return this;
        }
        public Builder clearResp() {
          result.hasResp = false;
          result.resp_ = nettytest.ConvQClientProto.ClientMessage.ServerResponse.ResponseType.OK;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:nettytest.ClientMessage.ServerResponse)
      }
      
      static {
        defaultInstance = new ServerResponse(true);
        nettytest.ConvQClientProto.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:nettytest.ClientMessage.ServerResponse)
    }
    
    // optional .nettytest.ClientMessage.ClientRequest req = 1;
    public static final int REQ_FIELD_NUMBER = 1;
    private boolean hasReq;
    private nettytest.ConvQClientProto.ClientMessage.ClientRequest req_;
    public boolean hasReq() { return hasReq; }
    public nettytest.ConvQClientProto.ClientMessage.ClientRequest getReq() { return req_; }
    
    // optional .nettytest.ClientMessage.ServerResponse resp = 2;
    public static final int RESP_FIELD_NUMBER = 2;
    private boolean hasResp;
    private nettytest.ConvQClientProto.ClientMessage.ServerResponse resp_;
    public boolean hasResp() { return hasResp; }
    public nettytest.ConvQClientProto.ClientMessage.ServerResponse getResp() { return resp_; }
    
    private void initFields() {
      req_ = nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDefaultInstance();
      resp_ = nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasReq()) {
        if (!getReq().isInitialized()) return false;
      }
      if (hasResp()) {
        if (!getResp().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasReq()) {
        output.writeMessage(1, getReq());
      }
      if (hasResp()) {
        output.writeMessage(2, getResp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasReq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReq());
      }
      if (hasResp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nettytest.ConvQClientProto.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nettytest.ConvQClientProto.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nettytest.ConvQClientProto.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private nettytest.ConvQClientProto.ClientMessage result;
      
      // Construct using nettytest.ConvQClientProto.ClientMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new nettytest.ConvQClientProto.ClientMessage();
        return builder;
      }
      
      protected nettytest.ConvQClientProto.ClientMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new nettytest.ConvQClientProto.ClientMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nettytest.ConvQClientProto.ClientMessage.getDescriptor();
      }
      
      public nettytest.ConvQClientProto.ClientMessage getDefaultInstanceForType() {
        return nettytest.ConvQClientProto.ClientMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public nettytest.ConvQClientProto.ClientMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private nettytest.ConvQClientProto.ClientMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public nettytest.ConvQClientProto.ClientMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        nettytest.ConvQClientProto.ClientMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nettytest.ConvQClientProto.ClientMessage) {
          return mergeFrom((nettytest.ConvQClientProto.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nettytest.ConvQClientProto.ClientMessage other) {
        if (other == nettytest.ConvQClientProto.ClientMessage.getDefaultInstance()) return this;
        if (other.hasReq()) {
          mergeReq(other.getReq());
        }
        if (other.hasResp()) {
          mergeResp(other.getResp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              nettytest.ConvQClientProto.ClientMessage.ClientRequest.Builder subBuilder = nettytest.ConvQClientProto.ClientMessage.ClientRequest.newBuilder();
              if (hasReq()) {
                subBuilder.mergeFrom(getReq());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReq(subBuilder.buildPartial());
              break;
            }
            case 18: {
              nettytest.ConvQClientProto.ClientMessage.ServerResponse.Builder subBuilder = nettytest.ConvQClientProto.ClientMessage.ServerResponse.newBuilder();
              if (hasResp()) {
                subBuilder.mergeFrom(getResp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setResp(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .nettytest.ClientMessage.ClientRequest req = 1;
      public boolean hasReq() {
        return result.hasReq();
      }
      public nettytest.ConvQClientProto.ClientMessage.ClientRequest getReq() {
        return result.getReq();
      }
      public Builder setReq(nettytest.ConvQClientProto.ClientMessage.ClientRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasReq = true;
        result.req_ = value;
        return this;
      }
      public Builder setReq(nettytest.ConvQClientProto.ClientMessage.ClientRequest.Builder builderForValue) {
        result.hasReq = true;
        result.req_ = builderForValue.build();
        return this;
      }
      public Builder mergeReq(nettytest.ConvQClientProto.ClientMessage.ClientRequest value) {
        if (result.hasReq() &&
            result.req_ != nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDefaultInstance()) {
          result.req_ =
            nettytest.ConvQClientProto.ClientMessage.ClientRequest.newBuilder(result.req_).mergeFrom(value).buildPartial();
        } else {
          result.req_ = value;
        }
        result.hasReq = true;
        return this;
      }
      public Builder clearReq() {
        result.hasReq = false;
        result.req_ = nettytest.ConvQClientProto.ClientMessage.ClientRequest.getDefaultInstance();
        return this;
      }
      
      // optional .nettytest.ClientMessage.ServerResponse resp = 2;
      public boolean hasResp() {
        return result.hasResp();
      }
      public nettytest.ConvQClientProto.ClientMessage.ServerResponse getResp() {
        return result.getResp();
      }
      public Builder setResp(nettytest.ConvQClientProto.ClientMessage.ServerResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasResp = true;
        result.resp_ = value;
        return this;
      }
      public Builder setResp(nettytest.ConvQClientProto.ClientMessage.ServerResponse.Builder builderForValue) {
        result.hasResp = true;
        result.resp_ = builderForValue.build();
        return this;
      }
      public Builder mergeResp(nettytest.ConvQClientProto.ClientMessage.ServerResponse value) {
        if (result.hasResp() &&
            result.resp_ != nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDefaultInstance()) {
          result.resp_ =
            nettytest.ConvQClientProto.ClientMessage.ServerResponse.newBuilder(result.resp_).mergeFrom(value).buildPartial();
        } else {
          result.resp_ = value;
        }
        result.hasResp = true;
        return this;
      }
      public Builder clearResp() {
        result.hasResp = false;
        result.resp_ = nettytest.ConvQClientProto.ClientMessage.ServerResponse.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nettytest.ClientMessage)
    }
    
    static {
      defaultInstance = new ClientMessage(true);
      nettytest.ConvQClientProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nettytest.ClientMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nettytest_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nettytest_ClientMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nettytest_ClientMessage_ClientRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nettytest_ClientMessage_ClientRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nettytest_ClientMessage_ServerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nettytest_ClientMessage_ServerResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025conveyormessage.proto\022\tnettytest\"\377\002\n\rC" +
      "lientMessage\0223\n\003req\030\001 \001(\0132&.nettytest.Cl" +
      "ientMessage.ClientRequest\0225\n\004resp\030\002 \001(\0132" +
      "\'.nettytest.ClientMessage.ServerResponse" +
      "\032\210\001\n\rClientRequest\022?\n\003req\030\001 \002(\01622.nettyt" +
      "est.ClientMessage.ClientRequest.RequestT" +
      "ype\022\013\n\003msg\030\002 \001(\014\")\n\013RequestType\022\007\n\003PUT\020\000" +
      "\022\010\n\004PEEK\020\001\022\007\n\003POP\020\002\032w\n\016ServerResponse\022B\n" +
      "\004resp\030\001 \002(\01624.nettytest.ClientMessage.Se" +
      "rverResponse.ResponseType\"!\n\014ResponseTyp",
      "e\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001B\035\n\tnettytestB\020ConvQ" +
      "ClientProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nettytest_ClientMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nettytest_ClientMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nettytest_ClientMessage_descriptor,
              new java.lang.String[] { "Req", "Resp", },
              nettytest.ConvQClientProto.ClientMessage.class,
              nettytest.ConvQClientProto.ClientMessage.Builder.class);
          internal_static_nettytest_ClientMessage_ClientRequest_descriptor =
            internal_static_nettytest_ClientMessage_descriptor.getNestedTypes().get(0);
          internal_static_nettytest_ClientMessage_ClientRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nettytest_ClientMessage_ClientRequest_descriptor,
              new java.lang.String[] { "Req", "Msg", },
              nettytest.ConvQClientProto.ClientMessage.ClientRequest.class,
              nettytest.ConvQClientProto.ClientMessage.ClientRequest.Builder.class);
          internal_static_nettytest_ClientMessage_ServerResponse_descriptor =
            internal_static_nettytest_ClientMessage_descriptor.getNestedTypes().get(1);
          internal_static_nettytest_ClientMessage_ServerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nettytest_ClientMessage_ServerResponse_descriptor,
              new java.lang.String[] { "Resp", },
              nettytest.ConvQClientProto.ClientMessage.ServerResponse.class,
              nettytest.ConvQClientProto.ClientMessage.ServerResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
